apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: user
    secureJsonData:
      password: password
    database: analytics
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
