apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: your_user
    secureJsonData:
      password: your_password
    database: your_database_name
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
